django_train/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

    path('', include('account.urls')),
    path('shop/', include('shop.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
]

shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.ProductListView.as_view(), name='shop'),
    path('ajax/products-search/', views.HeaderSearchView.as_view(), name='ajax-products-search'),
    path('shop/search/', views.SearchResultsView.as_view(), name='search'),
    path('product-create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<int:id>', views.add_to_cart, name='add-to-cart'),
    path('remove-one-from-cart/<int:id>', views.remove_one_from_cart, name='remove-one-from-cart'),
    path('remove-from-cart/<int:id>', views.remove_from_cart, name='remove-from-cart'),

]

shop/models.py
from django.db import models
from datetime import datetime
from django.shortcuts import reverse
from django.template.defaultfilters import slugify

from account.models import Profile


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, default="test-slug")
    price = models.FloatField(null=True)
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, null=True, blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    available = models.BooleanField(default=True)
    date_created = models.DateTimeField(default=datetime.now, null=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/product/%i" % self.id

    def get_absolute_update_url(self):
        return "/product/%i/update" % self.id

    def get_absolute_delete_url(self):
        return "/product/%i/delete" % self.id

    def get_add_to_cart_url(self):
        return reverse("shop:add-to-cart", kwargs={
            'id': self.id
        })

    def get_remove_one_from_cart_url(self):
        return reverse("shop:remove-one-from-cart", kwargs={
            'id': self.id
        })

    def get_remove_from_cart_url(self):
        return reverse("shop:remove-from-cart", kwargs={
            'id': self.id
        })


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    customer = models.ForeignKey(Profile, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Cart'

    def __str__(self):
        return f"{self.quantity} of {self.product.name} in cart of {self.customer.user.username}"

    def get_quantity(self):
        return self.quantity

    def get_products_price(self):
        return self.quantity*self.product.price


class BillingData(models.Model):
    customer = models.ForeignKey(Profile, null=True, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    delivery = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} from {self.city}"


class OrderedProduct(models.Model):
    order_number = models.PositiveIntegerField(null=False, blank=False, default=1)
    copy_of_product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"#{self.order_number} | {self.quantity} of {self.copy_of_product.name}"


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivering', 'Delivering'),
        ('Delivered', 'Delivered')
    )

    customer = models.ForeignKey(Profile, null=True, on_delete=models.SET_NULL)
    ordered_product = models.ManyToManyField(OrderedProduct)
    billing_data = models.ForeignKey(
        BillingData, related_name='billing_data', on_delete=models.SET_NULL, blank=True, null=True)
    ordered_date = models.DateTimeField(default=datetime.now, null=True)
    order_number = models.PositiveIntegerField(null=False, blank=False, default=1)
    status = models.CharField(
        max_length=200, null=True, choices=STATUS, default='Pending')
    tags = models.ManyToManyField(Tag, blank=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return '{} ordered in {}'.format(self.customer.user.username, self.ordered_date)

shop/views.py
from django.views.generic import ListView, DetailView, FormView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.db.models import Q
from django.core import serializers
from random import randint
import json

from account.models import Profile
from . import models
from . import forms
# Create your views here.


def create_order_number(n):
    return n+1


class HeaderSearchView(View):
    model = models.Product
    template_name = "shop/shop_header.html"

    def post(self, *args, **kwargs):
        searched_str = json.loads(self.request.body).get('searchBar')
        print('searched_str', searched_str)

        products = models.Product.objects.filter(
            name__icontains=searched_str
        )[:5]
        p_val = products.values('id', 'name')
        data = []
        i = 0
        for product in p_val:
            obj = {
                'id': product['id'],
                'name': product['name'],
                'absolute_url': products[i].get_absolute_url()
            }
            data.append(obj)
            i += 1
        return JsonResponse({'data': data})


class ProductListView(ListView):
    model = models.Product
    queryset_products = models.Product.objects.all()

    paginate_by = 3

    context_object_name = 'product_list'
    template_name = "shop/shop.html"


class ProductDetailView(DetailView):
    model = models.Product
    context_object_name = 'object'
    template_name = "shop/product-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset_products = models.Product.objects.all()
        context['product_list'] = queryset_products
        return context


class ProductCreateView(CreateView):
    model = models.Product
    fields = ['name', 'price', 'category', 'description', 'image', 'available']
    template_name = 'shop/product-form.html'
    success_url = 'shop:shop'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['info'] = 'create'
        return context


class ProductUpdateView(UpdateView):
    model = models.Product
    fields = ['name', 'price', 'category', 'description', 'image', 'available']
    template_name = 'shop/product-form.html'
    success_url = 'shop:shop'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['info'] = 'update'
        return context


class ProductDeleteView(DeleteView):
    model = models.Product
    template_name = 'shop/confirm-delete.html'
    success_url = reverse_lazy('shop')


class CartView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            profile = Profile.objects.get(user=request.user)
            cart = models.Cart.objects.filter(customer=profile)
            total_price = 0
            for product in cart.all():
                total_price += product.get_products_price()

            context = {
                'object': cart,
                'total_price': total_price,
            }
            return render(request, 'shop/cart.html', context)
        except ObjectDoesNotExist:
            context = {
                'object': ''
            }
            messages.warning(request, "You do not have an active order")
            # return render(request, 'shop/cart.html', context)
            return redirect('shop:shop')


class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        profile = Profile.objects.get(user=self.request.user)
        try:
            form = forms.CheckoutForm()
            context = {
                'form': form,
            }
            return render(self.request, 'shop/checkout.html', context)
        except ObjectDoesNotExist:
            messages.warning(
                self.request, "You do not have items in your cart!")
            return redirect('shop:shop')

    def post(self, *args, **kwargs):
        profile = Profile.objects.get(user=self.request.user)
        cart = models.Cart.objects.filter(customer=profile)
        billing_qs = models.BillingData.objects.filter(customer=profile)

        form = forms.CheckoutForm(self.request.POST or None)
        try:
            if form.is_valid():
                first_name = form.cleaned_data.get('first_name')
                last_name = form.cleaned_data.get('last_name')
                phone_number = form.cleaned_data.get('phone_number')
                email = form.cleaned_data.get('email')
                city = form.cleaned_data.get('city')
                delivery = form.cleaned_data.get('delivery')
                payment_option = form.cleaned_data.get('payment_option')

                if billing_qs.exists():
                    models.BillingData.objects.filter(customer=profile).update(
                        customer=profile,
                        first_name=first_name,
                        last_name=last_name,
                        phone_number=phone_number,
                        email=email,
                        city=city,
                        delivery=delivery
                    )
                else:
                    models.BillingData.objects.create(
                        customer=profile,
                        first_name=first_name,
                        last_name=last_name,
                        phone_number=phone_number,
                        email=email,
                        city=city,
                        delivery=delivery
                    )

                ordered_product = models.OrderedProduct.objects.last()
                if ordered_product is None:
                    order_number = 1
                else:
                    order_number = create_order_number(
                        ordered_product.order_number)

                order = models.Order.objects.create(
                    customer=profile,
                    billing_data=models.BillingData.objects.get(
                        customer=profile),
                    order_number=order_number
                )

                for p in cart:
                    o_product = models.OrderedProduct.objects.create(
                        order_number=order_number,
                        copy_of_product=p.product,
                        quantity=p.quantity
                    )
                    order.ordered_product.add(o_product)

                cart.delete()

                messages.success(self.request, "Thanks, order created!")
                return redirect('shop:shop')
            else:
                messages.warning(
                    self.request, "Form is not valid. Please, try again!")
                return redirect('shop:shop')
        except ObjectDoesNotExist:
            messages.warning(
                self.request, "You do not have products in your cart!")
            return redirect('shop:shop')


def add_to_cart(request, id):
    product = get_object_or_404(models.Product, id=id)
    profile = Profile.objects.get(user=request.user)
    ordered_product = models.Cart.objects.filter(
        customer=profile,
        product=product,
    )

    if ordered_product.exists():
        cart = ordered_product[0]
        cart.quantity += 1
        cart.save()

        messages.success(request, 'Product quantity was updated!')
        return redirect('shop:cart')
    else:
        ordered_product = models.Cart.objects.create(
            customer=profile,
            product=product
        )

        messages.success(request, 'Product has been added to cart!')
        return redirect('shop:cart')
        

def remove_one_from_cart(request, id):
    product = get_object_or_404(models.Product, id=id)
    profile = Profile.objects.get(user=request.user)
    ordered_product = models.Cart.objects.filter(
        customer=profile,
        product=product,
    )

    if ordered_product.exists():
        cart = ordered_product[0]

        if cart.quantity == 1:
            return remove_from_cart(request, id)
        else:
            cart.quantity -= 1

        cart.save()

        messages.success(request, 'Product quantity was updated!')
        return redirect('shop:cart')
    else:
        messages.error(request, 'Product was not in your cart!')
        return redirect('shop:cart')


def remove_from_cart(request, id):
    model_product = get_object_or_404(models.Product, id=id)
    profile = Profile.objects.get(user=request.user)
    ordered_product = models.Cart.objects.filter(
        customer=profile,
        product=model_product,
    )
    if ordered_product.exists():
        ordered_product = ordered_product[0]
        ordered_product.delete()

        messages.success(request, 'Product quantity was deleted!')
        return redirect('shop:cart')
    else:

        messages.error(request, 'Product was not in your cart!')
        return redirect('shop:cart')


class SearchResultsView(ListView):
    model = models.Product
    template_name = 'shop/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = models.Product.objects.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query)
        )
        return object_list

templates/shop/cart.html
{% extends "shop/shop.html" %}

{% load static %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
  
{% include "shop/shop_header.html" %}


  <div>
      <p style="text-align: center; font-size: xx-large; font:bold;">Cart</p>
  </div>

  <div>
    <table class="table" style="margin-left: auto; margin-right: auto; max-width: 900px;">
      <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Product</th>
          <th scope="col" style="text-align: center;">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>

      
      {% if object %}
      
        

      {% for item in object %}
      
        
      <tbody>
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ item.product.name }}</td>
          <td style="text-align: center;">
            <a href="{{ item.product.get_remove_one_from_cart_url }}" type="button" class="btn btn-light" style="width: 30px; height: 30px; margin-top: -11px">-</a>
            {{ item.quantity }} 
            <a href="{{ item.product.get_add_to_cart_url }}" type="button" class="btn btn-light" style="width: 30px; height: 30px; margin-top: -12px">+</a>
          </td>
          <td>$ {{ item.get_products_price }}
            <a href="{{ item.product.get_remove_from_cart_url }}" type="button" class="btn btn-light" style="width: 20px; height: 10px; margin-top: -8px; float:right">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
      <tfoot>
        <td></td>
        <td></td>
        <td>Total price: {{ total_price }}
          <a href="{% url 'shop:checkout' %}" type="button" class="btn btn-danger" disabled>Make order</a>
        </td>
      </tfoot>

      {% else %}
        
        <tfoot>
          <td></td>
          <td></td>
          <td>Your cart is empty! 
            <button type="button" class="btn btn-danger" disabled>Make order</button>
          </td>
        </tfoot>
      {% endif %}

    </table>
  </div>
    
{% endblock content %}

templates/shop/checkout.html
{% extends "shop/shop.html" %}

{% load static %}

{% block title %}Checkout page{% endblock title %}

{% block content %}
  
{% include "shop/shop_header.html" %}

    <div style="font-size: x-large; font:bold; text-align:center">
        Checkout page
    </div>

    <form class="row g-3" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="col-md-6">
        <label class="form-label">First Name</label>
          {{ form.first_name }}
        </span>
      </div>
      <div class="col-md-6">
        <label class="form-label">Last Name</label>
        {{ form.last_name }}
      </div>
      <div class="col-12">
        <label class="form-label">Phone Number</label>
        {{ form.phone_number }}
      </div>
      <div class="col-12">
        <label class="form-label">Email</label>
        {{ form.email }}
      </div>
      <div class="col-12" style="max-width: 200px">
        <label class="form-label">City</label>
        {{ form.city }}
      </div>
      <div class="col-12" style="max-width: 200px">
        <label class="form-label">Delivery method</label>
        {{ form.delivery }}
      </div>

      <div class="col-sm-10">
        <label class="form-label">Payment method</label>
        {% for value, name in form.fields.payment_option.choices %}
          <div class="form-check">
            <input class="form-check-input" type="radio" name="payment_option" id="{{ name }}" value="{{ value }}" required>
            <label class="form-check-label" for="{{ name }}">
              {{ name }}
            </label>
          </div>
          
        {% endfor %}
      </div>
      
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Payment</button>
      </div>
    </form>
    
{% endblock content %}

templates/shop/confirm-delete.html
{% block content %}
{% include "shop/shop_header.html" %}


  <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
  </form>
  
{% endblock content %}

templates/shop/product-detail.html
{% extends "shop/shop.html" %}

{% load static %}

{% block title %}
{{ object.name }} 
{% endblock title %}

{% block content %}
  
{% include "shop/shop_header.html" %}

    <div style="font-size: x-large; font:bold; text-align:center">
        Product page
    </div>

    <div>
      <p style="font-size: large;">{{ object.name }} - ${{ object.price }}</p>
      <p style="font-size: large;">Category: {{ object.category }}</p>
      <p style="font-size: large;">Description: {{ object.description }}</p>
      <p style="font-size: large;">Date created: {{ object.date_created }}</p>
      <p style="font-size: large;">Date updated: {{ object.date_updated }}</p>
      <p>
        Image: 
        <img src="{{ object.image.url }}" style="width: 150px; height:auto">
      </p>
    </div>


    <hr>
    <a href="{{ object.get_add_to_cart_url }}">Add to cart</a>

    <hr>
    <a href="{{ object.get_absolute_update_url }}">Update item</a>

    <hr>
    <a href="{{ object.get_absolute_delete_url }}">Delete item</a>
    
{% endblock content %}

templates/shop/product-form.html
{% extends "index.html" %}

{% load static %}

{% block title %}
<title>{{ object.name }}</title> 
{% endblock title %}

{% block content %}

{% include "shop/shop_header.html" %}

    <div>
      
      {% if info == 'create' %}
      <p style="font-size: large;">Create product</p>
      {% else %}
      <p style="font-size: large;">Update product</p>
      {% endif %}
        
      <form enctype="multipart/form-data" method="post" style="margin-left: 30px">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
    </div>
    <hr>

{% endblock content %}

templates/shop/search_results.html
<h1>Search Results</h1>

<ul>
  {% for city in object_list %}
    <li>
      {{ city.name }}, {{ city.state }}
    </li>
  {% endfor %}
</ul>

templates/shop/shop.html
{% extends 'index.html' %} 
{% load static %} 


{% block title %} Shop {% endblock title %} 

{% block extra_head %}
<link rel="stylesheet" href="{% static 'shop/styles.css' %}">

{% endblock extra_head %}

{% block content %}

{% include "shop/shop_header.html" %}

<div>
  <p style="font-size:xx-large; color:black; text-align: center">List of products</p>
  <div style="margin-left: 30px">
    {% for product in product_list %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <a href="{{ product.get_absolute_url }}">{{ product.name }} - ${{ product.price }}</a>
        </h5>
        <p class="card-text">
          {{ product.description }}
        </p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Details</a>
      </div>
    </div>
    <hr>
    {% endfor %}
  </div>
</div>

<div class="pagination" style="margin: auto; padding: 5px;">
  <span class="step-links" style="width: 100%; text-align: center;">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

<hr />
<div style="margin-top: 30px; margin-bottom: 30px">
  <a href="{% url 'shop:product-create' %}" style="font-size: large"
    >Create new product</a
  >
</div>
<hr />

{% endblock content %}

templates/shop/shop_header.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'homepage' %}">Homepage</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:shop' %}">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:cart' %}">Cart</a>
        </li>

      </ul>
      <form action="{% url 'shop:search' %}" autocomplete="off" class="d-flex " method="GET">
        {% csrf_token %}
        <div class="autocomplete" style="width:fit-content">
          <input class="form-control me-2" id="searchBar" name="q" type="search" placeholder="Search" aria-label="Search">
        </div>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
  </div>
</nav>




<script>
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  const csrftoken = getCookie('csrftoken');


  function autocomplete(inp, arr, data) {
    var currentFocus;
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        closeAllLists();
        if (!val) { return false;}
        currentFocus = -1;
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        this.parentNode.appendChild(a);
        for (i = 0; i < arr.length; i++) {
          if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
            b = document.createElement("DIV");
            b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
            b.innerHTML += arr[i].substr(val.length);
            b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
            b.addEventListener("click", function(e) {
                inp.value = this.getElementsByTagName("input")[0].value;
                closeAllLists();
                redirectToProductPage(inp.value, data);
            });
            a.appendChild(b);
          }
        }
    });

    inp.addEventListener("keydown", function(e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
          currentFocus++;
          addActive(x);
        } else if (e.keyCode == 38) { //up
          currentFocus--;
          addActive(x);
        } else if (e.keyCode == 13) {
          e.preventDefault();
          if (currentFocus > -1) {
            if (x) x[currentFocus].click();
          }
        }
    });

    function addActive(x) {
      if (!x) return false;
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }

    function closeAllLists(elmnt) {
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }

    function redirectToProductPage(inpVal, data) {
      console.log('inpVal', inpVal)

      data.map((d) => {
        if(inpVal === d.name){
          window.location = d.absolute_url
        }
      })

      
    }

    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });
  }


  const suggestions = document.querySelector('.suggestions ul');
  var input = document.getElementById("searchBar")


  function search(str, data) {
    let results = [];
    let product_names = [];
    const val = str.toLowerCase();

    data.map((i) => {
      product_names.push(i.name)
    })
  
    for (i = 0; i < product_names.length; i++) {
      if (product_names[i].toLowerCase().indexOf(val) > -1) {
        results.push(product_names[i]);
      }
    }
  
    return results;
  }
  function searchHandler(e) {
    const inputVal = e.target.value;
    let results = [];


    if(e.target.value.length > 1) {
      var url = '{% url "shop:ajax-products-search" %}';
      fetch(url, {
        method: "POST",
        headers:{
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
          'X-CSRFToken': csrftoken,
        },
        body: JSON.stringify({ 'searchBar': e.target.value }),
      })
      .then((res) => res.json())
      .then((data) => {
        results = search(inputVal, data.data);
        autocomplete(document.getElementById("searchBar"), results, data.data);
      })
    }
  }

  input.addEventListener('input', searchHandler);

</script>