account/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views

app_name = 'account'

urlpatterns = [
    # path('', views.homepage, name='homepage'),
    path('login/', views.loginUser, name='login'),
    path('register/', views.registerUser, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', views.profilePage, name='profile'),
   

    path('staff-only/', views.staff_only, name='staff-only'),
    path('free-access/', views.free_access, name='free-access'),

]

django_train/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

    path('', include('account.urls')),
    path('shop/', include('shop.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
]

report/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name='report'

urlpatterns = [
    path('', views.EntriesView.as_view(), name='entries'),
    path('entrie/<username>/<int:pk>', views.EntriesDetailView.as_view(), name='entries-detail'),
    path('entrie/stats/', views.EntriesStatsView.as_view(), name='entries-stats'),
    path('entrie/create', views.EntriesCreateView.as_view(), name='entries-create'),
    path('entrie/<int:pk>/delete', views.EntriesDeleteView.as_view(), name='entries-delete'),
]

shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.ProductListView.as_view(), name='shop'),
    path('ajax/products-search/', views.HeaderSearchView.as_view(), name='ajax-products-search'),
    path('shop/search/', views.SearchResultsView.as_view(), name='search'),
    path('product-create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<int:id>', views.add_to_cart, name='add-to-cart'),
    path('remove-one-from-cart/<int:id>', views.remove_one_from_cart, name='remove-one-from-cart'),
    path('remove-from-cart/<int:id>', views.remove_from_cart, name='remove-from-cart'),

]

templates/homepage.html
{% extends "index.html" %} 
{% load static %} 

{% block title %}Home{% endblock title %} 

{% block content %}
<div class="h3" style="text-align: center;">Homepage</div>

<div style="margin-left: 10px">
  <p class="h4">Authorization</p>
  <div style="margin-left: 30px">
    <a href="{% url 'account:login' %}">login</a>
    <br />
    <a href="{% url 'account:register' %}">register</a>
    <br />
    <a href="{% url 'account:logout' %}">logout</a>
  </div>
  <p class="h4">Permissions</p>
  <div style="margin-left: 30px">
    
    {% if user.is_staff %} 
    <a href="{% url 'account:staff-only' %}">staff-only</a>
    <br />
    {% else %}
    <p>Staff-only page is hidden, You do not have a permession.</p>
    {% endif %}
    <a href="{% url 'account:free-access' %}">free-access</a>
  </div>
  <p class="h4">Profile</p>
  <div style="margin-left: 30px">
    {% if request.user.is_authenticated %} 
    <a href="{% url 'account:profile' %}">Profile</a>
    {% else %}
    <p>You are not authenticated.</p>
    {% endif %}  
  </div>
</div>

  <hr>

<div style="margin-left: 10px; margin-top: 10px">
  <p class="h4">Shop (products / orders / cart)</p>
  <div style="margin-left: 30px">
    {% if request.user.is_authenticated %} 
    <a href="{% url 'shop:shop' %}">Shop</a>
    {% else %}
    <p>You are not authenticated.</p>
    {% endif %}  
  </div>
</div>

<div style="margin-left: 10px; margin-top: 10px">
  <p class="h4">Report page (Entries / data / statistics)</p>
  <div style="margin-left: 30px">
    {% if request.user.is_authenticated %} 
    <a href="{% url 'report:entries' %}">Report</a>
    {% else %}
    <p>You are not authenticated.</p>
    {% endif %}  
  </div>
</div>
{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% block extra_head %}{% endblock extra_head %}
    
    <title>{% block title %}Homepage{% endblock %}</title>
  </head>
  <body>
    {% include "site/header.html" %}
    
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    
    {% block content %}{% endblock content %}
    
    
    {% include "site/scripts.html" %}
  </body>
</html>