account/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views

app_name = 'account'

urlpatterns = [
    # path('', views.homepage, name='homepage'),
    path('login/', views.loginUser, name='login'),
    path('register/', views.registerUser, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', views.profilePage, name='profile'),
   

    path('staff-only/', views.staff_only, name='staff-only'),
    path('free-access/', views.free_access, name='free-access'),

]

django_train/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),

    path('', include('account.urls')),
    path('shop/', include('shop.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
]

report/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name='report'

urlpatterns = [
    path('', views.EntriesView.as_view(), name='entries'),
    path('entrie/<username>/<int:pk>', views.EntriesDetailView.as_view(), name='entries-detail'),
    path('entrie/stats/', views.EntriesStatsView.as_view(), name='entries-stats'),
    path('entrie/create', views.EntriesCreateView.as_view(), name='entries-create'),
    path('entrie/<int:pk>/delete', views.EntriesDeleteView.as_view(), name='entries-delete'),
]

report/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class EntriesStatistics(models.Model):
    week_number = models.PositiveIntegerField(null=True)
    amount_of_entries = models.PositiveIntegerField(null=True)
    total_distance = models.FloatField(null=True)
    total_duration = models.DurationField()
    weekly_average_speed = models.FloatField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.week_number}"
    
    def get_distance_in_km(self):
        return self.total_distance/1000
    
    def get_duration_in_seconds(self):
        return self.total_duration.total_seconds()
    
    def get_weekly_average_speed(self):
        hours = self.get_duration_in_seconds()/60/60
        res = self.get_distance_in_km()/hours
        return "%.1f" % res


class Entries(models.Model):
    date = models.DateTimeField(default=datetime.now)
    week_number = models.PositiveIntegerField(null=True)
    distance = models.FloatField(null=False)
    duration = models.DurationField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.date}"
    
    def get_absolute_url(self):
        return f"/entrie/{self.user.username}/{self.id}"
    
    def get_absolute_delete_url(self):
        return f"/report/entrie/{self.id}/delete"

    def get_distance_in_km(self):
        return self.distance/1000

    def get_duration_in_seconds(self):
        return self.duration.total_seconds()
    
    def get_average_speed(self):
        hours = self.get_duration_in_seconds()/60/60
        res = self.get_distance_in_km()/hours
        return "%.1f" % res

report/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models

class ReportCreateForm(forms.ModelForm):
  class Meta:
    model = models.Entries
    fields = ['date', 'distance', 'duration']
    widgets = {
            'date': forms.DateTimeInput(format=('%d/%m/%Y %H:%M'), 
                                             attrs={'type':'datetime-local', 'style':'width:220px'}),
            'distance': forms.NumberInput(attrs={'type': 'number', 'style':'width:220px'}),
            'duration': forms.TimeInput(attrs={'type': 'text', 'step': 2, 'value':'00:15:15', 'class':'html-duration-picker', 'style':'width:95px'})
        }

report/views.py
from django.conf import settings
from django.shortcuts import render
from django.db.models.functions import ExtractWeek, ExtractMonth, ExtractYear
from django.db.models import Sum, Count
from django.views.generic import ListView, DetailView, FormView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from datetime import date, datetime, timedelta
from django.utils import timezone
import json, pytz

from . import models, forms


class EntriesView(LoginRequiredMixin, View):
    login_url = 'account:readme_page'
    template_name = 'report/entries.html'
    context = {}

    def get(self, *args, **kwargs):
        qs = models.Entries.objects.filter(user=self.request.user)
        entries = qs.order_by('-date')
        date_min = self.request.GET.get('date_min')
        date_max = self.request.GET.get('date_max')
        date_ordering = self.request.GET.get('orderingSelect')

        if self.is_valid_queryparam(date_ordering):
            entries = qs.order_by(date_ordering)

        if self.is_valid_queryparam(date_min):
            entries = entries.filter(date__gte=date_min)

        if self.is_valid_queryparam(date_max):
            entries = entries.filter(date__lt=date_max)
        
        self.context['data'] = entries
        return render(self.request, self.template_name, self.context)
    
    def is_valid_queryparam(self, param):
        return param != '' and param is not None


class EntriesStatsView(LoginRequiredMixin, ListView):
    login_url = 'account:readme_page'
    context_object_name = 'weeks'
    template_name = 'report/stats.html'

    def get_queryset(self):
        queryset = models.EntriesStatistics.objects.filter(user=self.request.user)[:53]
        return queryset


class EntriesDetailView(DetailView):
    model = models.Entries
    context_object_name = 'object'
    template_name = "report/entries-detail.html"


class EntriesCreateView(LoginRequiredMixin, CreateView):
    login_url = 'account:readme_page'

    model = models.Entries
    form_class = forms.ReportCreateForm
    template_name = 'report/entrie-form.html'
    success_url = reverse_lazy('report:entries')

    def form_valid(self, form):
        form_date = form.cleaned_data['date']
        distance = form.cleaned_data['distance']
        duration = form.cleaned_data['duration']
        week_num = form_date.isocalendar()[1]
        qs = models.EntriesStatistics.objects.filter(
            user=self.request.user, 
            week_number=week_num
        )

        # add to Entries form creation
        form.instance.user = self.request.user
        form.instance.week_number = week_num

        if qs.exists():
            qs = qs[0]
            qs.amount_of_entries = qs.amount_of_entries+1
            qs.total_distance=qs.total_distance+float(distance)
            qs.total_duration=qs.total_duration+duration
            qs.save()
        else:
            stats = models.EntriesStatistics.objects.create(
                week_number=week_num,
                amount_of_entries=1,
                total_distance=distance,
                total_duration=duration,
                user=self.request.user
            )
        return super().form_valid(form)
    

class EntriesDeleteView(DeleteView):
    model = models.Entries
    template_name = 'report/confirm-delete.html'
    success_url = reverse_lazy('report:entries')

    def get_object(self, queryset=None):
        obj = super(EntriesDeleteView, self).get_object()
        return obj

    def post(self, request, *args, **kwargs):
        obj = self.get_object()

        entr_stat = models.EntriesStatistics.objects.get(week_number=obj.week_number)
        if entr_stat.amount_of_entries == 1:
            entr_stat.delete()
        else:
            entr_stat.amount_of_entries = entr_stat.amount_of_entries - 1
            entr_stat.total_distance = entr_stat.total_distance - float(obj.distance)
            entr_stat.total_duration = entr_stat.total_duration - obj.duration
            entr_stat.save()
        return self.delete(request, *args, **kwargs)

    

templates/report/confirm-delete.html
{% extends 'report/entries.html' %}

{% load static %}

{% block title %}
Delete confirmation
{% endblock title %}

{% block content %}
{% include "report/report-header.html" %}

<div style="margin: 30px;">

  <form method="post">{% csrf_token %}
    <h2 style="text-align: center;">Are you sure you want to delete this entrie?</h2>
    <input 
    class="btn btn-lg btn-danger" 
    type="submit" 
    style="
    margin: 0;
    margin-top:50px;
    position: absolute;
    left: 50%;
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    " 
    value="Confirm">
  </form>
  
</div>
{% endblock content %}

templates/report/entrie-form.html
{% extends "report/entries.html" %}

{% load static %}

{% block title %}
{{ object.name }}
{% endblock title %}

{% block extra_head %}
<script src="https://cdn.jsdelivr.net/npm/html-duration-picker/dist/html-duration-picker.min.js"></script>
{% endblock extra_head %}

{% block content %}
{% include "report/report-header.html" %}
  
<form method="POST">
  {% csrf_token %}
  <div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
      <div class="col-sm-6 col-md-4 col-md-offset-4">
        <h1 class="text-center login-title">Create new entrie</h1>
        <div class="account-wall">
              <div style="margin: 10px;">
                <label for="datetime">Date</label>
                {{form.date}}
              </div>
              <div style="margin: 10px;">
                <label for="distance">Distance (Meters)</label>
                {{form.distance}}
              </div>
              <div style="margin: 10px;">
                <label for="duration">Duration</label>
                {{form.duration}}
              </div>

              <button 
                class="btn btn-lg btn-warning btn-block" 
                type="submit" 
                value="Login"
                style="margin-right:auto; margin-left: auto; display: block; width: 50%; margin-top:15px; margin-bottom:20px;"
              >
                  Create
              </button>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock content %}

templates/report/entries-detail.html
{% extends "report/entries.html" %}

{% load static %}

{% block title %}
{{ object.username }}
{% endblock title %}

{% block content %}
{% include "report/report-header.html" %}

    <div style="font-size: x-large; font:bold; text-align:center">
        Entrie page of {{object.date}}
    </div>

    <div>
      <p style="font-size: large;">Distance: {{ object.distance }} meters</p>
      <p style="font-size: large;">Duration: {{ object.duration }}</p>
      <p style="font-size: large;">Date: {{ object.date }}</p>
      <p style="font-size: large;">Average speed: {{ object.get_average_speed }}</p>
    </div>


    <hr>
    <a href="{{ object.get_absolute_delete_url }}">Delete item</a>
    
{% endblock content %}

templates/report/entries.html
{% extends "index.html" %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

{% block content %}
{% include "report/report-header.html" %}
    

<h2 style="font-weight: bold; text-align:center;">This is your entries</h2>
  
  <br>

  <form id="form" method="GET" name="form" class="form-inline container-lg" style="padding: 15px">
    <div class="input-group mb-3">
      <div style="margin: 15px">
        <label for="date_min">From Date</label>
        <input id="date_min" name="date_min" type="date" class="form-control" style="width: 300px;" />
      </div>
      <div style="margin: 15px">
        <label for="date_max">To Date</label>
        <input id="date_max" name="date_max" type="date" class="form-control" style="width: 300px;" />
      </div>
      
      <div style="margin: 15px">
        <label for="orderingSelect">Ordering</label>
        <select 
          class="form-select" 
          id='orderingSelect' 
          name='orderingSelect' 
          aria-label="Default select example"
          style="width: 200px;"
          >
          <option selected value="-date">-date</option>
          <option value="date">date</option>
        </select>
      </div>
    </div>

    <button type="submit" id="submit_date" class="btn btn-lg btn-warning" style="margin-left: 15px; margin-top: -10px">Filter</button>
  </form>

  <!-- ENTRIES TABLE -->

  <table class="table table-success table-striped container-lg" style="text-align: center;">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Distance, Km</th>
        <th scope="col">Duration, H:M:S</th>
        <th scope="col">Date</th>
        <th scope="col">Average speed, Km/h</th>
        <th scope="col">Del</th>
      </tr>
    </thead>
    <tbody id="entries-result" class="container" style="margin-top: 20px;">
      <!-- Here will render GETed Entries -->
      {% for entrie in data %}
      <tr>

        <th>{{entrie.id}}</th>
        <td>{{entrie.get_distance_in_km}}</td>
        <td>{{entrie.duration}}</td>
        <td>{{entrie.date}}</td>
        <td>{{entrie.get_average_speed}}</td>
        <td>
          <a class="btn btn-outline-danger" href="{{entrie.get_absolute_delete_url}}">Delete</a>
        </td>
      </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

templates/report/report-header.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'report:entries' %}">Entries</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'report:entries-stats' %}">Statictics</a>
          </li>
          
        </ul>
        <ul class="navbar-nav me-right mb-2 mb-md-0">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'report:entries-create' %}" style="margin-right: 30px;">Create entrie</a>
          </li>

          {% if request.user.is_authenticated %}

          <span class="navbar-text" style="margin-right: 30px;">
            {{request.user.username}}
          </span>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'account:logout' %}">Logout</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'account:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Register</a>
          </li>
          {% endif %}
          
        </ul>

        
      </div>
    </div>
  </nav>

templates/report/stats.html
{% extends "report/entries.html" %}
{% load static %}
{% block title %}
  Statistics
{% endblock title %}

{% block content %}
{% include "report/report-header.html" %}

<h2 style="font-weight: bold; text-align:center;">Last Year statistics</h2>
  
  <br>

  <form id="form" name="form" class="form-inline container-lg" style="padding: 15px">
    <div class="input-group mb-3">
      <div style="margin: 15px">
        <label for="date_min">From Date</label>
        <input id="date_min" name="date_min" type="date" class="form-control" style="width: 300px;" />
      </div>
      <div style="margin: 15px">
        <label for="date_max">To Date</label>
        <input id="date_max" name="date_max" type="date" class="form-control" style="width: 300px;" />
      </div>
      
      <div style="margin: 15px">
        <label for="orderingSelect">Ordering</label>
        <select 
          class="form-select" 
          id='orderingSelect' 
          name='orderingSelect' 
          aria-label="Default select example"
          style="width: 200px;"
          >
          <option selected value="-date">-date</option>
          <option value="date">date</option>
        </select>
      </div>
    </div>

    <button type="submit" id="submit_date" class="btn btn-lg btn-warning" style="margin-left: 15px; margin-top: -10px">Filter</button>
  </form>

  <table class="table table-success table-striped container-lg" style="text-align: center;">
    <thead>
      <tr>
        <th scope="col">Week №</th>
        <th scope="col">Amount of Entries</th>
        <th scope="col">Total distance</th>
        <th scope="col">Total duration</th>
        <th scope="col">Weekly average speed, Km/h</th>
      </tr>
    </thead>
    <tbody id="entries-result" class="container" style="margin-top: 20px;">
      <!-- Here will render GETed Entries -->
      {% for week in weeks %}
      <tr>
        <th>{{week.week_number}}</th>
        <td>{{week.amount_of_entries}}</td>
        <td>{{week.total_distance}}</td>
        <td>{{week.total_duration}}</td>
        <td>{{week.get_weekly_average_speed}}</td>
      </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}